
repos:
-   repo: https://github.com/lightspeed-hospitality/pre-commit-hooks.git
    rev: v0.7.29
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: circleci-config-validate
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '^(poetry.lock)$'
    -   id: black
    -   id: ruff
    -   id: pylint
    -   id: isort
