version: "3.8"

services:
  guardian:
    build:
      context: .
      args:
        MODULE_NAME: "guardian"
        EXTRA_INDEX_URLS: >-
          --extra-index-url https://${PYPI_USER}:${PYPI_RWD_TOKEN}@lightspeedhq.jfrog.io/artifactory/api/pypi/pypi-local/simple"
    environment:
      AUTHENTICATION_ENABLED: 0
      ENABLE_RELOAD: 1
      ENABLE_PRETTY_JSON_LOGS: 1
      LOG_LEVEL: "debug"
    networks:
      - internal
    ports:
      - "8080:8080"

  dynamodb:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb
   networks:
    - internal
   volumes:
     - dynamodb-data:/home/dynamodb/data
   working_dir: /home/dynamodb

networks:
  internal:

volumes:
  dynamodb-data:
